---
os: linux
language: python
python:
- '3.8'
services:
- docker

env:
  global:
  # 'Stable' version number regex.
  # Used to test strings against the pattern "N.N[.N]",
  # i.e. a 2 or 3-field version string of digits separated by periods.
  - V_REGEX='^([0-9]+\.){1,2}[0-9]+$'

stages:
- name: test
- name: publish latest
#  if: branch == master
- name: publish tag
  if: tag IS present
- name: publish stable
  if: tag IS present AND tag =~ ${V_REGEX}

before_install:
# Downstream project triggers (used when we're tagged)
# The downstream projects are the Fragalsyss Stack and Fragalysis Loader.
# The user can define the following variables in their Travis Settings.
# If they're not defined then apply sensible defaults.
- export BE_NAMESPACE=${BE_NAMESPACE-xchem}
- export STACK_NAMESPACE=${STACK_NAMESPACE:-xchem}
- export STACK_BRANCH=${STACK_BRANCH:-master}
- export STACK_VARS=${STACK_VARS:--}
- export LOADER_NAMESPACE=${LOADER_NAMESPACE:-xchem}
- export LOADER_BRANCH=${LOADER_BRANCH:-master}
- export LOADER_VARS=${LOADER_VARS:--}

install:
# Always build a container image
# (tagging with the required project name)
- docker build -t ${BE_NAMESPACE}/fragalysis-backend:latest .
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- >-
    curl
    --location
    --retry 3
    https://raw.githubusercontent.com/informaticsmatters/trigger-travis/master/requirements.txt
    --output trigger-travis-requirements.txt
- >-
    curl
    --location
    --retry 3
    https://raw.githubusercontent.com/informaticsmatters/trigger-travis/master/trigger-travis.py
    --output trigger-travis.py
- pip install -r trigger-travis-requirements.txt
- chmod +x trigger-travis.py

jobs:
  include:

  # Test-stage jobs...

  - stage: test
    name: Container Test
    script:
    - docker-compose -f docker-compose.test.yml up --build --exit-code-from tests --abort-on-container-exit

  # Publish-stage jobs...
  # Every successful master build results in a latest image
  # and every tag results in a tagged image in Docker Hub.
  # Tags that match V_REGEX are considered 'official' tags
  # and also result in a 'stable' image tag.

  - stage: publish latest
    name: Latest Container
    script:
    - docker push ${BE_NAMESPACE}/fragalysis-backend:latest

  - stage: publish tag
    name: Tagged Container
    script:
    - docker tag ${BE_NAMESPACE}/fragalysis-backend:latest ${BE_NAMESPACE}/fragalysis-backend:${TRAVIS_TAG}
    - docker push ${BE_NAMESPACE}/fragalysis-backend:${TRAVIS_TAG}

  - stage: publish stable
    name: Stable Container
    script:
    - docker tag ${BE_NAMESPACE}/fragalysis-backend:latest ${BE_NAMESPACE}/fragalysis-backend:stable
    - docker push ${BE_NAMESPACE}/fragalysis-backend:stable
    # A new 'official' image (and latest and tag)
    # Trigger the stack and loader downstream projects...
    - >-
        ./trigger-travis.py
        ${STACK_NAMESPACE} fragalysis-stack ${TRAVIS_ACCESS_TOKEN}
        --branch ${STACK_BRANCH}
        --vars ${STACK_VARS}
    - >-
        ./trigger-travis.py
        ${LOADER_NAMESPACE} fragalysis-loader ${TRAVIS_ACCESS_TOKEN}
        --branch ${LOADER_BRANCH}
        --vars ${LOADER_VARS}
