---

# In your Travis Settings...
#
# Set PUBLISH_IMAGES to 'yes' to enable publishing to Docker Hub
# You will also need to provide values for  DOCKER_USERNAME and DOCKER_PASSWORD.
# Set TRIGGER_DOWNSTREAM to 'yes' to enable downstream project triggering.
# Enabling TRIGGER_DOWNSTREAM is only effective if PUBLISH_IMAGES is also set.
#
# Projects triggered by activity in this repository are: -
#
#   ${STACK_NAMESPACE}/fragalysis-stack
#   ${LOADER_NAMESPACE}/fragalysis-loader

os: linux
language: python
python:
- '3.8'
services:
- docker

stages:
- name: publish latest
- name: trigger downstream
  if: |
    branch = im-travis \
    AND env(PUBLISH_IMAGES) = yes
- name: publish tag
  if: |
    tag IS present \
    AND env(PUBLISH_IMAGES) = yes
- name: publish stable
  if: |
    tag IS present \
    AND tag =~ ^([0-9]+\.){1,2}[0-9]+$ \
    AND env(PUBLISH_IMAGES) = yes

# Global variables
# (available to the Job matrix)...
env:
  global:
  # The origin of the trigger code
  - TRIGGER_ORIGIN=https://raw.githubusercontent.com/informaticsmatters/trigger-travis/master

before_install:
# Downstream project triggers (used when we're tagged)
# The downstream projects are the Fragalsyss Stack and Fragalysis Loader.
# The user can define the following variables in their Travis Settings.
# If they're not defined then apply sensible defaults.
- export BE_NAMESPACE=${BE_NAMESPACE-xchem}
- export STACK_NAMESPACE=${STACK_NAMESPACE:-xchem}
- export STACK_BRANCH=${STACK_BRANCH:-master}
- export STACK_VARS=BE_IMAGE_TAG=latest,BE_NAMESPACE=${BE_NAMESPACE}
- export LOADER_NAMESPACE=${LOADER_NAMESPACE:-xchem}
- export LOADER_BRANCH=${LOADER_BRANCH:-master}
- export LOADER_VARS=BE_IMAGE_TAG=latest,BE_NAMESPACE=${BE_NAMESPACE}
- echo ${PUBLISH_IMAGES}
- echo ${TRIGGER_DOWNSTREAM}

install:
# Login to docker and download trigger code
- curl --location --retry 3 ${TRIGGER_ORIGIN}/requirements.txt --output trigger-travis-requirements.txt
- curl --location --retry 3 ${TRIGGER_ORIGIN}/trigger-travis.py --output trigger-travis.py
- pip install -r trigger-travis-requirements.txt
- chmod +x trigger-travis.py

jobs:
  include:

  # Test-stage jobs...

  - stage: publish latest
    name: Test and Latest Container
    script:
    - docker build -t ${BE_NAMESPACE}/fragalysis-backend:latest .
    - docker-compose -f docker-compose.test.yml up --build --exit-code-from tests --abort-on-container-exit
    - if [ ${PUBLISH_IMAGES} == "yes" ]; then
      docker push ${BE_NAMESPACE}/fragalysis-backend:latest;
      fi

  # Publish-stage jobs...
  # Every successful master build results in a latest image (above)
  # and every tag results in a tagged image in Docker Hub.
  # Tags that match a RegEx are considered 'official' tags
  # and also result in a 'stable' image tag.

  - stage: publish tag
    name: Tagged Container
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -t ${BE_NAMESPACE}/fragalysis-backend:${TRAVIS_TAG} .
    - docker push ${BE_NAMESPACE}/fragalysis-backend:${TRAVIS_TAG}

  - stage: publish stable
    name: Stable Container
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker pull ${BE_NAMESPACE}/fragalysis-backend:${TRAVIS_TAG}
    - docker tag ${BE_NAMESPACE}/fragalysis-backend:${TRAVIS_TAG} ${BE_NAMESPACE}/fragalysis-backend:stable
    - docker push ${BE_NAMESPACE}/fragalysis-backend:stable

  - stage: trigger downstream
    name: Trigger Downstream
    script:
    - echo "STACK_NAMESPACE=${STACK_NAMESPACE}"
    - echo "STACK_BRANCH=${STACK_BRANCH}"
    - echo "STACK_VARS=${STACK_VARS}"
    - ./trigger-travis.py --pro ${STACK_NAMESPACE} fragalysis-stack ${TRAVIS_ACCESS_TOKEN} --branch ${STACK_BRANCH} --vars ${STACK_VARS}
    - echo "LOADER_NAMESPACE=${LOADER_NAMESPACE}"
    - echo "LOADER_BRANCH=${LOADER_BRANCH}"
    - echo "LOADER_VARS=${LOADER_VARS}"
    - ./trigger-travis.py --pro ${LOADER_NAMESPACE} fragalysis-loader ${TRAVIS_ACCESS_TOKEN} --branch ${LOADER_BRANCH} --vars ${LOADER_VARS}
