---
version: '3'

services:
  postgres:
    image: postgres:12.2
    volumes:
    - ../django_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fragalsyis
      POSTGRES_PASSWORD: fragalysis
      POSTGRES_DB: frag
      PGDATA: /var/lib/postgresql/data/pgdata
  tests:
    image: ${BE_NAMESPACE}/fragalysis-backend:latest
    command: ["/code/wait-for-it.sh", "postgres:5432", "--", "/bin/bash", "/code/test_entry.sh"]
    volumes:
    - .:/code
    - ../logs:/code/logs/
    - ../media:/code/media/
    ports:
    - "80:80"
    depends_on:
    - postgres
