---
version: '3'

services:

  # The database
  database:
    image: postgres:12.2
    container_name: database
    volumes:
    - ../data/postgre/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: fragalysis
      POSTGRES_USER: fragalysis
      POSTGRES_DB: frag
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"

  # The graph
  graph:
    image: neo4j:4.4.2
    container_name: graph
    ports:
    # Comment these two out in production
    - "7474:7474"
    - "7687:7687"
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    volumes:
    - ../data/neo4j/data:/data
    - ../data/neo4j/logs:/logs
    environment:
    - NEO4J_AUTH=none
    - NEO4J_dbms_memory_pagecache_size=4G

  # The stack (backend)
  stack:
    container_name: stack
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash /code/launch-stack.sh
    volumes:
    - ../data/logs:/code/logs/
    - ../data/media:/code/media/
    - ../fragalysis-frontend:/code/frontend/
    - .:/code/
    environment:
      POSTGRESQL_DATABASE: frag
      POSTGRESQL_USER: fragalysis
      POSTGRESQL_PASSWORD: fragalysis
      POSTGRESQL_HOST: database
      POSTGRESQL_PORT: 5432
      # Default Debug to true for local development
      DEBUG_FRAGALYSIS: 'True'
      DISABLE_LOGGING_FRAMEWORK: 'No'
      OIDC_RP_CLIENT_SECRET: 'c6245428-04c7-466f-9c4f-58c340e981c2'
      SQUONK_UI_URL: https://data-manager-ui.xchem-dev.diamond.ac.uk/data-manager-ui
      SQUONK_API_URL: https://data-manager.xchem-dev.diamond.ac.uk/data-manager-api
      # Celery tasks run synchronously?
#      CELERY_TASK_ALWAYS_EAGER: 'True'
    ports:
    - "8080:80"
    depends_on:
    - database
    - graph
